# SPDX-FileCopyrightText: 2024 Shell Global Solutions International B.V. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: SonarCloudAnalysis

on:
  workflow_call:

jobs:
  SonarCloudAnalysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Specify all python versions you might want to perform the actions on
        python-version: [ "3.11" ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: SonarCloud Scan
        if: ${{ always() }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PYELQ_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload SonarCloud Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: sonar-scan-log
          path: .scannerwork/report-task.txt
        if: ${{ always() }}
